[grpc]
ip = "127.0.0.1" # Required - gRPC bind hostname/address.
port = 8009 # Required - gRPC bind port

[engine]
cache_time = 1 # Required - Cache disk sync time in minutes.
flush_time = 10 # Required - Flush time in minutes.
dir = "./rusdb" # Optional - Default "./rusdb"

[logging] # Optional - Default: None
path = "./rusdb.log" # Optional - Default: "./rusdb.log" - Relative paths place it inside of the data directory.
level = 4 # Optional - Default: 2 (LevelFilter::Info) - Anything outside of 0-5 will be LevelFilter::Trace.
